server:
    port: 8080

spring:
    application:
        name: SWE-CSCI361
    datasource:
        url: jdbc:mysql://localhost:3306/swe_csci361
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
    servlet:
        multipart:
            max-file-size: 1GB
            max-request-size: 1GB
logging:
    level:
        org:
            hibernate.SQL: DEBUG
            hibernate.type.descriptor.sql.BasicBinder: TRACE

amazon:
    aws:
        access-key: ?
        secret-key: ?
#logging:
#    level:
#        org:
#            springframework:
#                security: DEBUG
